/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2013 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package net.pixelfactor.installreferrer;

import android.content.SharedPreferences;

import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;

import org.appcelerator.titanium.TiApplication;
import org.appcelerator.kroll.common.Log;

@Kroll.module(name="Installreferrer", id="net.pixelfactor.installreferrer")
public class InstallreferrerModule extends KrollModule
{

	// Standard Debugging variables
	private static final String TAG = "net.pixelfactor.installreferrer";
	static SharedPreferences settings;

	// You can define constants with @Kroll.constant, for example:
	// @Kroll.constant public static final String EXTERNAL_NAME = value;
	
	public InstallreferrerModule()
	{
		super();
	}

	@Kroll.onAppCreate
	public static void onAppCreate(TiApplication app)
	{
		settings = app.getSharedPreferences("installPreferences", 0);
	}

	// Methods
	@Kroll.method
	public String getUtmSource() {
		String referralUrl = settings.getString("INSTALL_REFERRER", null);
		
		if (referralUrl != null && !referralUrl.equals("")) {
			return referralUrl;
		}
		
		return null;
	}
	
	// Properties
	@Kroll.getProperty
	public String getExampleProp()
	{
		Log.d(TAG, "get example property");
		return "hello world";
	}
	
	
	@Kroll.setProperty
	public void setExampleProp(String value) {
		Log.d(TAG, "set example property: " + value);
	}

}

